  
apiVersion: app.m4d.ibm.com/v1alpha1
kind: M4DModule
metadata:
  name: hello-world-read-module
  labels:
    name: hello-world-read-module
    version: 0.0.1  # semantic version
  namespace: m4d-system
spec:
  chart:
    name: ghcr.io/mohammad-nassar10/hello-world-read-module-chart:v0.0.1
    values:
      image.tag: v0.0.1
  flows:
    - read
  capabilities:
    actions:
      - id: redact-ID
        level: 2  # column
    api:
      protocol: s3
      dataformat: csv
    supportedInterfaces:
    - flow: read
      source:
        protocol: s3
        dataformat: parquet
    - flow: read
      source:
        protocol: s3
        dataformat: csv
  statusIndicators:
    - kind: hello-world-read-module
      successCondition: status.status == SUCCEEDED
      failureCondition: status.status == FAILED
      errorMessage: status.error