name: Build

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

env:
  DOCKER_HOSTNAME: ghcr.io


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

        
    - name: Build docker image 
      run: make docker-build
    - name: Docker login
      if: ${{ github.event_name != 'pull_request' }}
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login -u "${{ github.actor }}" --password-stdin "${{ env.DOCKER_HOSTNAME }}"
    - name: Docker push
      if: ${{ (github.event_name != 'pull_request') && contains(github.ref, 'tags') }}
      #run: docker push ghcr.io/mohammad-nassar10/hello-world-read-module:${{ matrix.TAG }}
      run: make docker-push
    - id: version
      name: Infer version
      run: echo ::set-output name=version::${GITHUB_REF#refs/*/}
   # - name: Retag image for tag
    #  if: contains(github.ref, 'tags')
     # run: docker tag ghcr.io/mohammad-nassar10/hello-world-read-module:${{ matrix.TAG }} ghcr.io/mohammad-nassar10/hello-world-read-module:${{ steps.version.outputs.version }}${{ matrix.RELEASE_TAG_SUFFIX }}
    - run: docker images
    #- name: Push image for tag
     # if: contains(github.ref, 'tags')
      #run: docker push ghcr.io/mohammad-nassar10/hello-world-read-module:${{ steps.version.outputs.version }}${{ matrix.RELEASE_TAG_SUFFIX }}
        
    #- name: Build helm chart 
      #run: make helm-verify
     # run: helm install rel1-hello-world-read-module hello-world-read-module
    - name: Helm login
      if: ${{ github.event_name != 'pull_request' }}
      run: export HELM_EXPERIMENTAL_OCI=1 && echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login -u "${{ github.actor }}" --password-stdin "${{ env.DOCKER_HOSTNAME }}"
    - name: Helm chart push
      if: ${{ (github.event_name != 'pull_request') && !contains(github.ref, 'tags') }}
      #run: helm chart save hello-world-read-module ghcr.io/mohammad-nassar10/hello-world-read-module-chart:${{ matrix.TAG }} && helm chart push ghcr.io/mohammad-nassar10/hello-world-read-module-chart:${{ matrix.TAG }} && helm chart remove ghcr.io/mohammad-nassar10/hello-world-read-module-chart:${{ matrix.TAG }}
      run: make helm-chart-push
    #- name: Helm uninstall
     # run: make helm-uninstall
